"""Public contract surface shared by API, graph, gateways and repositories.

This module re-exports the versioned Pydantic models defined in
:mod:`backend.app.models.contracts` so that downstream code can write
``from backend.app.models import TaskFrame`` without depending on the
internal module layout. The LLM-facing structured drafts
(``QueryDraft``, ``TaskUnderstanding``, ``ThreadTitleDraft``) live in
:mod:`backend.app.graph.state` and are deliberately not re-exported
here to avoid an import cycle through ``backend.app.graph``.
"""

from __future__ import annotations

from .contracts import (
    Action,
    AgentState,
    AppError,
    ArtifactRecord,
    ArtifactSpec,
    ArtifactType,
    CatalogField,
    CatalogObject,
    ChatRequest,
    ChatResponse,
    Checkpoint,
    ContextFrame,
    Contract,
    ConversationMessage,
    CoverageResult,
    CoverageStatus,
    EvaluationEvidence,
    FilterSpec,
    GroundedContext,
    IdentityResponse,
    Intent,
    Interrupt,
    JoinPath,
    ModelUsage,
    MutationPreview,
    MutationSpec,
    PasswordLoginRequest,
    PermissionContext,
    PreferenceUpdate,
    QueryPlan,
    QuerySpec,
    RecommendedQuestionsResponse,
    RegisterRequest,
    RegistrationResponse,
    ResultObservation,
    ResultPage,
    ResultStatus,
    ResultSummary,
    ResumeRequest,
    RollingSummary,
    RunStatus,
    RuntimeEvent,
    SchemaGap,
    ScopeMode,
    SummaryFact,
    TaskFrame,
    ThreadDetail,
    ThreadListResponse,
    ThreadSummary,
    TimeRange,
    TokenResponse,
    TraceContext,
    TraceFields,
    UserPreferences,
)

__all__ = [
    "Action",
    "AgentState",
    "AppError",
    "ArtifactRecord",
    "ArtifactSpec",
    "ArtifactType",
    "CatalogField",
    "CatalogObject",
    "ChatRequest",
    "ChatResponse",
    "Checkpoint",
    "ContextFrame",
    "Contract",
    "ConversationMessage",
    "CoverageResult",
    "CoverageStatus",
    "EvaluationEvidence",
    "FilterSpec",
    "GroundedContext",
    "IdentityResponse",
    "Intent",
    "Interrupt",
    "JoinPath",
    "ModelUsage",
    "MutationPreview",
    "MutationSpec",
    "PasswordLoginRequest",
    "PermissionContext",
    "PreferenceUpdate",
    "QueryPlan",
    "QuerySpec",
    "RecommendedQuestionsResponse",
    "RegisterRequest",
    "RegistrationResponse",
    "ResultObservation",
    "ResultPage",
    "ResultStatus",
    "ResultSummary",
    "ResumeRequest",
    "RollingSummary",
    "RunStatus",
    "RuntimeEvent",
    "SchemaGap",
    "ScopeMode",
    "SummaryFact",
    "TaskFrame",
    "ThreadDetail",
    "ThreadListResponse",
    "ThreadSummary",
    "TimeRange",
    "TokenResponse",
    "TraceContext",
    "TraceFields",
    "UserPreferences",
]
