/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat Stream */
        get: operations["chat_stream_api_chat_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{result_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Result */
        get: operations["result_api_results__result_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/results/{result_id}/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Result */
        get: operations["export_result_api_results__result_id__export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Threads */
        get: operations["threads_api_threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thread */
        get: operations["thread_api_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/interrupts/{interrupt_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_threads__thread_id__interrupts__interrupt_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Artifact */
        get: operations["artifact_api_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @enum {string}
         */
        Action: "RETRIEVE" | "GENERATE" | "EXECUTE" | "ASK_USER" | "RESPOND" | "END" | "FAIL";
        /** ArtifactRecord */
        ArtifactRecord: {
            spec: components["schemas"]["ArtifactSpec"];
            /** Payload */
            payload: unknown;
        };
        /** ArtifactSpec */
        ArtifactSpec: {
            /** Artifact Id */
            artifact_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Owner User Id */
            owner_user_id: string;
            type: components["schemas"]["ArtifactType"];
            /** Source Result Ids */
            source_result_ids?: string[];
            /** Source Ref */
            source_ref?: string | null;
            /** Permission Policy Version */
            permission_policy_version: string;
            /** Catalog Version */
            catalog_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Payload Ref */
            payload_ref: string;
            /**
             * Schema Version
             * @default artifact_v1
             */
            schema_version: string;
        };
        /**
         * ArtifactType
         * @enum {string}
         */
        ArtifactType: "FIELD_LIST" | "RESULT_TABLE" | "CSV" | "CHART_DSL";
        /** ChatRequest */
        ChatRequest: {
            /** Thread Id */
            thread_id?: string | null;
            /** Message */
            message: string;
            /** User Id */
            user_id?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Expected State Version */
            expected_state_version?: number | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Request Id */
            request_id: string;
            /** Thread Id */
            thread_id: string;
            status: components["schemas"]["RunStatus"];
            /** Answer */
            answer?: string | null;
            /** Result Ids */
            result_ids?: string[];
            /** Artifact Ids */
            artifact_ids?: string[];
            /** Events */
            events?: {
                [key: string]: unknown;
            }[];
            interrupt?: components["schemas"]["Interrupt"] | null;
            /** Trace Id */
            trace_id?: string | null;
            /** State Version */
            state_version?: number | null;
        };
        /** ConversationMessage */
        ConversationMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IdentityResponse */
        IdentityResponse: {
            /** User Id */
            user_id: string;
            /** Roles */
            roles?: string[];
            /** Policy Version */
            policy_version: string;
            /** Expires At */
            expires_at?: string | null;
        };
        /** Interrupt */
        Interrupt: {
            /**
             * Status
             * @default WAITING_FOR_USER
             * @constant
             */
            status: "WAITING_FOR_USER";
            /** Reason */
            reason: string;
            /** Question */
            question: string;
            /** Candidates */
            candidates?: string[];
            /**
             * Resume Node
             * @default agent_node
             */
            resume_node: string;
            /** Checkpoint Id */
            checkpoint_id: string;
            /** Interrupt Id */
            interrupt_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Schema Version
             * @default interrupt_v1
             */
            schema_version: string;
        };
        /** ModelUsage */
        ModelUsage: {
            /** Models */
            models?: string[];
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Model Duration Ms
             * @default 0
             */
            model_duration_ms: number;
        };
        /** PasswordLoginRequest */
        PasswordLoginRequest: {
            /** Account */
            account: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Account */
            account: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Confirm Password
             * Format: password
             */
            confirm_password: string;
            /**
             * Role
             * @enum {string}
             */
            role: "USER" | "ADMIN";
            /** Invite Code */
            invite_code: string;
        };
        /** RegistrationResponse */
        RegistrationResponse: {
            /**
             * Status
             * @default registered
             * @constant
             */
            status: "registered";
            /** Account */
            account: string;
            /**
             * Role
             * @enum {string}
             */
            role: "USER" | "ADMIN";
            /**
             * Schema Version
             * @default registration_response_v1
             * @constant
             */
            schema_version: "registration_response_v1";
        };
        /** RecommendedQuestionsResponse */
        RecommendedQuestionsResponse: {
            /** Items */
            items?: string[];
            /**
             * Schema Version
             * @default recommended_questions_v1
             * @constant
             */
            schema_version: "recommended_questions_v1";
        };
        /** PreferenceUpdate */
        PreferenceUpdate: {
            /**
             * Key
             * @enum {string}
             */
            key: "timezone" | "default_shop_id" | "chart_preference" | "number_format";
            /** Value */
            value: unknown;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /** ResultPage */
        ResultPage: {
            /** Result Id */
            result_id: string;
            /** Rows */
            rows?: {
                [key: string]: unknown;
            }[];
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
        };
        /** ResumeRequest */
        ResumeRequest: {
            /** User Id */
            user_id?: string | null;
            /** Answer */
            answer: string;
            /** Client Request Id */
            client_request_id: string;
            /** Expected State Version */
            expected_state_version: number;
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "RUNNING" | "WAITING_FOR_USER" | "SUCCEEDED" | "FAILED" | "REJECTED" | "TIMEOUT";
        /** RuntimeEvent */
        RuntimeEvent: {
            /**
             * Event
             * @enum {string}
             */
            event: "run.started" | "node.started" | "node.completed" | "interrupt.created" | "run.completed" | "run.failed" | "thread.title_updated";
            /** Request Id */
            request_id: string;
            /** Thread Id */
            thread_id: string;
            /** Node */
            node?: string | null;
            action?: components["schemas"]["Action"] | null;
            status: components["schemas"]["RunStatus"];
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Code */
            error_code?: string | null;
            /** Answer */
            answer?: string | null;
            /** Result Ids */
            result_ids?: string[];
            /** Artifact Ids */
            artifact_ids?: string[];
            interrupt?: components["schemas"]["Interrupt"] | null;
            /** State Version */
            state_version?: number | null;
            model_usage?: components["schemas"]["ModelUsage"] | null;
            /** Thread Title */
            thread_title?: string | null;
            /**
             * Schema Version
             * @default runtime_event_v1
             * @constant
             */
            schema_version: "runtime_event_v1";
        };
        /** ThreadDetail */
        ThreadDetail: {
            /** Thread Id */
            thread_id: string;
            status: components["schemas"]["RunStatus"];
            /** Messages */
            messages?: components["schemas"]["ConversationMessage"][];
            /** Result Ids */
            result_ids?: string[];
            /** Artifact Ids */
            artifact_ids?: string[];
            interrupt?: components["schemas"]["Interrupt"] | null;
            /** State Version */
            state_version?: number | null;
        };
        /** ThreadListResponse */
        ThreadListResponse: {
            /** Items */
            items?: components["schemas"]["ThreadSummary"][];
        };
        /** ThreadSummary */
        ThreadSummary: {
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
        };
        /** UserPreferences */
        UserPreferences: {
            /** Values */
            values?: {
                [key: string]: unknown;
            };
            /**
             * Schema Version
             * @default user_preferences_v1
             */
            schema_version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityResponse"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_get: {
        parameters: {
            query: {
                message: string;
                thread_id?: string | null;
                request_id?: string | null;
                expected_state_version?: number | null;
                timezone?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeEvent"];
                    "text/event-stream": components["schemas"]["RuntimeEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    result_api_results__result_id__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_result_api_results__result_id__export_csv_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                result_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    threads_api_threads_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    thread_api_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_threads__thread_id__interrupts__interrupt_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                interrupt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    artifact_api_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
