import {useEffect,useRef,useState,type FormEvent} from 'react'
import {requestJson} from './client'
import type {Action,ChartDsl,Identity,ResultPage,StreamEvent,ThreadSummary} from './types'

export function Login({onAuthenticated}:{onAuthenticated:(token:string)=>void}){
  const[account,setAccount]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState<string>(),[loading,setLoading]=useState(false)
  async function login(event:FormEvent){event.preventDefault();if(!account.trim()||!password){setError('请输入账号和密码。');return}setLoading(true);setError(undefined);try{const payload=await requestJson<{access_token:string}>('/api/auth/login',undefined,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({account:account.trim(),password})});onAuthenticated(payload.access_token)}catch(value){setError(value instanceof Error?value.message:'登录失败')}finally{setLoading(false)}}
  return <main className="login-page"><section className="login-panel" aria-label="登录"><div className="brand"><span className="brand-mark">DR</span><span>Data Runtime</span></div><p className="eyebrow">受控数据访问</p><h1>进入证据链</h1><p>使用应用账号登录，权限范围由服务端根据数据库身份重新计算。</p><form onSubmit={event=>void login(event)}><label htmlFor="account">账号</label><input id="account" name="account" autoComplete="username" value={account} onChange={event=>setAccount(event.target.value)}/><label htmlFor="password">密码</label><input id="password" name="password" type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)}/><button className="primary-button" disabled={loading}>{loading?'正在验证身份':'登录'}</button></form>{error&&<p className="error" role="alert">{error}</p>}</section></main>
}

export function ThreadList({threads,current,query,onQuery,onOpen,onNew}:{threads:ThreadSummary[];current?:string;query:string;onQuery:(value:string)=>void;onOpen:(id:string)=>void;onNew:()=>void}){
  const visible=threads.filter(item=>item.title.toLowerCase().includes(query.toLowerCase()))
  return <aside className="threads" aria-label="线程列表"><button className="new-thread" onClick={onNew}>＋ 新建问题</button><label className="search-label" htmlFor="thread-search">查找线程</label><input id="thread-search" className="thread-search" value={query} onChange={event=>onQuery(event.target.value)} placeholder="搜索标题"/><p className="eyebrow">最近会话</p><nav>{visible.length?visible.map(thread=><button key={thread.thread_id} className={`thread-item ${thread.thread_id===current?'active':''}`} onClick={()=>onOpen(thread.thread_id)}><b>{thread.title}</b><span>{new Date(thread.updated_at).toLocaleString()}</span></button>):<p className="thread-empty">{query?'没有匹配的线程。':'完成第一次分析后，线程会出现在这里。'}</p>}</nav></aside>
}

export function Evidence({events}:{events:StreamEvent[]}){
  const stages:Action[]=['RETRIEVE','GENERATE','EXECUTE','RESPOND'],completed=[...events].reverse().find(event=>event.event==='run.completed'),usage=completed?.model_usage
  return <aside className="evidence" aria-label="证据栏" aria-live="polite"><div className="evidence-head"><span className="eyebrow">公开证据</span><span className="version">实时 SSE</span></div><h2>运行轨迹</h2><div className="rail">{stages.map((stage,index)=>{const done=[...events].reverse().find(event=>event.action===stage&&event.event==='node.completed'),started=[...events].reverse().find(event=>event.action===stage&&event.event==='node.started');return <div className={`rail-item ${done||started?'seen':''}`} key={stage}><span className="rail-dot">{done?'✓':index+1}</span><div><b>{stage}</b><small>{done?`${done.duration_ms??0} ms`:started?'运行中':'等待中'}</small>{done?.error_code&&<em>{done.error_code}</em>}</div></div>})}</div>{usage&&<dl className="usage"><div><dt>模型</dt><dd>{usage.models?.join(', ')||'—'}</dd></div><div><dt>Token</dt><dd>{usage.input_tokens??0} in / {usage.output_tokens??0} out</dd></div><div><dt>模型耗时</dt><dd>{usage.model_duration_ms??0} ms</dd></div></dl>}{events.length>0&&<details className="trace"><summary>查看公开事件（{events.length}）</summary>{events.map((event,index)=><div key={event.eventId??index}><code>{event.event}</code><span>{event.node??'runtime'} · {event.action??'—'}</span></div>)}</details>}</aside>
}

export function Chart({dsl,result}:{dsl:ChartDsl;result:ResultPage}){
  const ref=useRef<HTMLDivElement>(null)
  useEffect(()=>{let disposed=false,cleanup=()=>{};void import('echarts').then(echarts=>{if(disposed||!ref.current)return;const chart=echarts.init(ref.current),rows=result.rows??[],categories=rows.map(row=>String(row[dsl.category_field]??'')),values=rows.map(row=>Number(row[dsl.value_field]??0));chart.setOption({animationDuration:350,grid:{left:52,right:24,top:30,bottom:46},tooltip:{trigger:'axis'},xAxis:dsl.type==='horizontal_bar'?{type:'value'}:{type:'category',data:categories},yAxis:dsl.type==='horizontal_bar'?{type:'category',data:categories}:{type:'value'},series:[{type:dsl.type==='line'?'line':'bar',data:values,itemStyle:{color:'#0e7c7b'}}],textStyle:{fontFamily:'IBM Plex Sans'}});const resize=()=>chart.resize();addEventListener('resize',resize);cleanup=()=>{removeEventListener('resize',resize);chart.dispose()}});return()=>{disposed=true;cleanup()}},[dsl,result])
  return <section className="chart-panel" aria-label="结果图表"><div className="result-heading"><b>受控图表</b><small>{dsl.category_field} × {dsl.value_field}</small></div><div ref={ref} className="chart-canvas"/></section>
}

export function ResultTable({result,onPage,onDownload}:{result:ResultPage;onPage:(offset:number)=>void;onDownload:()=>void}){
  const rows=result.rows??[],columns=rows[0]?Object.keys(rows[0]):[],page=Math.floor(result.offset/result.limit)+1,pages=Math.max(1,Math.ceil(result.total/result.limit))
  return <section className="result-panel" aria-label="查询结果"><div className="result-heading"><span><b>结果表</b><small>{result.total} 行 · {rows.length?result.offset+1:0}–{Math.min(result.offset+rows.length,result.total)}</small></span><button className="quiet-button" onClick={onDownload}>下载完整 CSV</button></div>{rows.length?<div className="table-wrap" tabIndex={0} aria-label="可横向滚动的结果表"><table><thead><tr>{columns.map(column=><th scope="col" key={column}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{columns.map(column=><td key={column}>{String(row[column]??'—')}</td>)}</tr>)}</tbody></table></div>:<div className="empty" role="status"><b>没有符合条件的数据</b><span>空结果不等于数值 0，可以尝试调整时间范围。</span></div>}<div className="pagination"><button disabled={result.offset===0} onClick={()=>onPage(Math.max(0,result.offset-result.limit))}>上一页</button><span aria-label={`第 ${page} 页，共 ${pages} 页`}>{page} / {pages}</span><button disabled={result.offset+result.limit>=result.total} onClick={()=>onPage(result.offset+result.limit)}>下一页</button></div></section>
}

export function Topbar({identity,threadId,requestId,connection,expiry,onLogout,onThreads,onEvidence}:{identity?:Identity;threadId?:string;requestId?:string;connection:string;expiry?:Date;onLogout:()=>void;onThreads:()=>void;onEvidence:()=>void}){
  return <header className="topbar"><div className="brand"><span className="brand-mark">DR</span><span>Data Runtime</span></div><button className="mobile-toggle" aria-label="打开线程列表" onClick={onThreads}>线程</button><div className="thread-label">{threadId??'新分析线程'} {requestId&&<span>· {requestId.slice(0,8)}</span>}</div><div className={`connection ${connection}`} role="status"><i/>{connection==='ready'?'已连接':connection==='running'?'正在执行':connection==='reconnecting'?'正在重连':'连接中断'}</div><button className="mobile-toggle" aria-label="打开证据栏" onClick={onEvidence}>证据</button><span className="identity" title={expiry?`令牌有效至 ${expiry.toLocaleString()}`:'令牌有效期由服务端校验'}>{identity?.user_id} · {(identity?.roles??[]).join('/')}</span><button className="quiet-button" onClick={onLogout}>退出</button></header>
}
