import {StrictMode,useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import type {components} from './api/schema'
import {API,ApiError,consumeSse,isChartDsl,newClientRequestId,requestJson,tokenExpiry} from './client'
import {Chart,Evidence,Login,ResultTable,ThreadList,Topbar} from './components'
import type {ArtifactRecord,ChartDsl,ChatResult,Identity,Interrupt,Message,ResultPage,StreamEvent,ThreadDetail,ThreadSummary,UserPreferences} from './types'
import './styles.css'

const PAGE_SIZE=50

function App({token,logout}:{token:string;logout:()=>void}){
  const[identity,setIdentity]=useState<Identity>(),[threads,setThreads]=useState<ThreadSummary[]>([]),[messages,setMessages]=useState<Message[]>([])
  const[question,setQuestion]=useState(''),[events,setEvents]=useState<StreamEvent[]>([]),[result,setResult]=useState<ResultPage>(),[resultId,setResultId]=useState<string>(),[chartDsl,setChartDsl]=useState<ChartDsl>()
  const[busy,setBusy]=useState(false),[threadId,setThreadId]=useState<string>(),[requestId,setRequestId]=useState<string>(),[stateVersion,setStateVersion]=useState<number>(),[interrupt,setInterrupt]=useState<Interrupt>(),[error,setError]=useState<string>()
  const[connection,setConnection]=useState<'ready'|'running'|'reconnecting'|'offline'>('ready'),[preferences,setPreferences]=useState<UserPreferences>({values:{},schema_version:'user_preferences_v1'}),[route,setRoute]=useState(location.pathname),[drawer,setDrawer]=useState<'threads'|'evidence'>(),[threadQuery,setThreadQuery]=useState('')
  const streamAbort=useRef<AbortController|null>(null),resumeKeys=useRef(new Map<string,string>())
  const showSettings=route==='/app/settings'

  function navigate(path:string,replace=false){replace?history.replaceState({},'',path):history.pushState({},'',path);setRoute(path)}
  async function refreshThreads(){const value=await requestJson<components['schemas']['ThreadListResponse']>('/api/threads',token);setThreads(value.items??[])}
  async function loadResult(id:string,offset=0){const value=await requestJson<ResultPage>(`/api/results/${id}?offset=${offset}&limit=${PAGE_SIZE}`,token);setResult(value);setResultId(id)}
  async function loadArtifacts(ids:string[]){setChartDsl(undefined);for(const id of ids){try{const record=await requestJson<ArtifactRecord>(`/api/artifacts/${id}`,token);if(record.spec.type==='CHART_DSL'&&isChartDsl(record.payload))setChartDsl(record.payload)}catch(value){setError(value instanceof Error?value.message:'结果制品无法读取')}}}
  async function openThread(id:string,push=true){try{setError(undefined);const detail=await requestJson<ThreadDetail>(`/api/threads/${id}`,token),historyMessages=detail.messages??[],resultIds=detail.result_ids??[];setThreadId(id);setMessages(historyMessages as Message[]);setStateVersion(detail.state_version??undefined);setInterrupt(detail.interrupt??undefined);setEvents([]);if(resultIds.at(-1))await loadResult(resultIds.at(-1)!);else{setResult(undefined);setResultId(undefined)}await loadArtifacts(detail.artifact_ids??[]);if(push)navigate(`/app/threads/${id}`);setDrawer(undefined)}catch(value){setError(value instanceof Error?value.message:'线程无法读取')}}

  useEffect(()=>{let active=true;void (async()=>{try{const[me,settings]=await Promise.all([requestJson<Identity>('/api/me',token),requestJson<UserPreferences>('/api/settings',token)]);if(!active)return;setIdentity(me);setPreferences(settings);await refreshThreads();const thread=location.pathname.match(/^\/app\/threads\/([^/]+)$/),directResult=location.pathname.match(/^\/app\/results\/([^/]+)$/);if(thread)await openThread(decodeURIComponent(thread[1]),false);else if(directResult)await loadResult(decodeURIComponent(directResult[1]))}catch(value){if(active){setError(value instanceof Error?value.message:'工作台初始化失败');if(value instanceof ApiError&&value.status===401)logout()}}})();const pop=()=>setRoute(location.pathname);addEventListener('popstate',pop);return()=>{active=false;removeEventListener('popstate',pop)}},[token])

  function rememberEvent(event:StreamEvent){setEvents(old=>event.eventId&&old.some(item=>item.eventId===event.eventId)?old:[...old,event])}
  async function handleRunEvent(event:StreamEvent){
    rememberEvent(event)
    if(event.event==='run.started'){setThreadId(event.thread_id);navigate(`/app/threads/${event.thread_id}`,true)}
    if(event.event==='interrupt.created'){setThreadId(event.thread_id);setStateVersion(event.state_version??undefined);setInterrupt(event.interrupt??undefined);navigate(`/app/threads/${event.thread_id}`,true);await refreshThreads()}
    if(event.event==='run.completed'){const ids=event.result_ids??[];setThreadId(event.thread_id);setStateVersion(event.state_version??undefined);setInterrupt(event.interrupt??undefined);setMessages(old=>[...old,{role:'assistant',content:event.answer??'运行结束'}]);if(ids[0])await loadResult(ids[0]);await loadArtifacts(event.artifact_ids??[]);navigate(`/app/threads/${event.thread_id}`,true);await refreshThreads()}
    if(event.event==='run.failed'){setThreadId(event.thread_id);setStateVersion(event.state_version??undefined);setMessages(old=>event.answer?[...old,{role:'assistant',content:event.answer}]:old);setError(new ApiError(event.error_code??'REQUEST_FAILED').message);navigate(`/app/threads/${event.thread_id}`,true)}
  }

  async function ask(){
    if(!question.trim()||busy)return
    const text=question.trim(),id=newClientRequestId(),controller=new AbortController(),params=new URLSearchParams({message:text,timezone:String(preferences.values?.timezone??'Asia/Shanghai'),request_id:id})
    if(threadId){params.set('thread_id',threadId);if(stateVersion!==undefined)params.set('expected_state_version',String(stateVersion))}
    const cursor={lastEventId:0},url=`${API}/api/chat/stream?${params}`;streamAbort.current=controller;setMessages(old=>[...old,{role:'user',content:text}]);setQuestion('');setRequestId(id);setBusy(true);setConnection('running');setError(undefined);setResult(undefined);setResultId(undefined);setChartDsl(undefined);setEvents([]);setInterrupt(undefined)
    try{for(let attempt=0;attempt<3;attempt++){try{await consumeSse({url,token,requestId:id,cursor,signal:controller.signal,onEvent:handleRunEvent});setConnection('ready');break}catch(value){if(controller.signal.aborted)throw value;if(!(value instanceof TypeError)||attempt===2)throw value;setConnection('reconnecting')}}}catch(value){if(controller.signal.aborted){setConnection('ready');setError('已停止接收进度。服务端可能仍在执行，可从线程列表重新打开。')}else{setConnection('offline');setError(value instanceof Error?value.message:'实时连接已中断，请重新打开线程。')}}finally{if(streamAbort.current===controller)streamAbort.current=null;setBusy(false)}
  }

  async function resume(answer:string){
    if(!interrupt||!threadId||busy)return
    const key=resumeKeys.current.get(interrupt.interrupt_id)??newClientRequestId();resumeKeys.current.set(interrupt.interrupt_id,key);setBusy(true);setError(undefined)
    try{if(stateVersion===undefined)throw new Error('缺少线程版本，请重新打开线程。');const payload=await requestJson<ChatResult>(`/api/threads/${threadId}/interrupts/${interrupt.interrupt_id}/resume`,token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({answer,client_request_id:key,expected_state_version:stateVersion})}),ids=payload.result_ids??[];resumeKeys.current.delete(interrupt.interrupt_id);setStateVersion(payload.state_version??undefined);setInterrupt(payload.interrupt??undefined);setMessages(old=>[...old,{role:'user',content:answer},{role:'assistant',content:payload.answer??'运行结束'}]);if(ids[0])await loadResult(ids[0]);await loadArtifacts(payload.artifact_ids??[]);await refreshThreads()}catch(value){setError(value instanceof Error?value.message:'恢复失败')}finally{setBusy(false)}
  }

  async function saveTimezone(value:string){try{setPreferences(await requestJson<UserPreferences>('/api/settings',token,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:'timezone',value,confirmed:true})}));setError(undefined)}catch(reason){setError(reason instanceof Error?reason.message:'偏好保存失败')}}
  async function downloadCsv(){if(!resultId)return;const response=await fetch(`${API}/api/results/${resultId}/export.csv`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){setError('CSV 导出失败，请确认结果仍在有效期内。');return}const url=URL.createObjectURL(await response.blob()),anchor=document.createElement('a');anchor.href=url;anchor.download=`${resultId}.csv`;anchor.click();URL.revokeObjectURL(url)}
  function newThread(){setThreadId(undefined);setMessages([]);setEvents([]);setResult(undefined);setResultId(undefined);setChartDsl(undefined);setInterrupt(undefined);setError(undefined);navigate('/app');setDrawer(undefined)}

  if(showSettings)return <main className="settings-page"><section className="settings-panel" aria-label="用户设置"><p className="eyebrow">已确认的长期偏好</p><h1>分析设置</h1><label htmlFor="timezone">默认时区</label><select id="timezone" value={String(preferences.values?.timezone??'Asia/Shanghai')} onChange={event=>void saveTimezone(event.target.value)}><option>Asia/Shanghai</option><option>UTC</option><option>America/New_York</option><option>Europe/London</option></select><p>显式查询条件始终优先于这里的默认值。</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary-button" onClick={()=>navigate('/app')}>返回工作台</button></section></main>

  const threadsPanel=<ThreadList threads={threads} current={threadId} query={threadQuery} onQuery={setThreadQuery} onOpen={id=>void openThread(id)} onNew={newThread}/>,evidencePanel=<Evidence events={events}/>
  return <div className="workbench"><Topbar identity={identity} threadId={threadId} requestId={requestId} connection={connection} expiry={tokenExpiry(token)} onLogout={logout} onThreads={()=>setDrawer('threads')} onEvidence={()=>setDrawer('evidence')}/><main className="layout">{threadsPanel}<section className="conversation" aria-label="对话区域"><div className="conversation-scroll"><div className="workspace-heading"><div><p className="eyebrow">分析工作台 / 证据驱动</p><h1>{messages.length?'分析记录':'今天要查什么？'}</h1><p className="intro">目录证据、执行节点和数据权限随问题实时更新。</p></div><button className="settings-link" onClick={()=>navigate('/app/settings')}>分析设置</button></div>{messages.map((message,index)=><div key={`${message.role}-${index}`} className={`bubble ${message.role==='user'?'user-bubble':'system-bubble'}`}><span className="bubble-label">{message.role==='user'?'你':'Runtime'}</span>{message.content}</div>)}{busy&&<div className="bubble system-bubble" aria-live="polite"><span className="pulse"/>{connection==='reconnecting'?'正在恢复实时连接…':'正在运行分析图…'}</div>}{interrupt&&<div className="interrupt-panel" role="status"><b>需要补充信息</b><p>{interrupt.question}</p><div>{(interrupt.candidates??[]).map(candidate=><button key={candidate} onClick={()=>void resume(candidate)} disabled={busy}>{candidate}</button>)}</div><form onSubmit={event=>{event.preventDefault();const input=new FormData(event.currentTarget).get('clarification');if(typeof input==='string'&&input.trim())void resume(input.trim())}}><label htmlFor="clarification">补充说明</label><div className="inline-input"><input id="clarification" name="clarification"/><button disabled={busy}>继续</button></div></form></div>}{chartDsl&&result&&<Chart dsl={chartDsl} result={result}/>} {result&&<ResultTable result={result} onPage={offset=>void loadResult(result.result_id,offset)} onDownload={()=>void downloadCsv()}/>} {error&&<div className="error" role="alert">{error}{threadId&&<button onClick={()=>void openThread(threadId,false)}>重新打开线程</button>}</div>}</div><div className="composer"><textarea aria-label="问题" value={question} onChange={event=>setQuestion(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();void ask()}}} placeholder="例如：昨天各品类 GMV 是多少？"/>{busy?<button className="stop-button" aria-label="停止接收进度" onClick={()=>streamAbort.current?.abort()}>停止</button>:<button className="send" aria-label="发送问题" onClick={()=>void ask()} disabled={!question.trim()}>发送 ↗</button>}<span className="hint">Enter 发送 · Shift + Enter 换行</span></div></section>{evidencePanel}</main>{drawer&&<div className="drawer-backdrop" role="presentation" onClick={()=>setDrawer(undefined)}><div className="drawer" role="dialog" aria-modal="true" aria-label={drawer==='threads'?'线程抽屉':'证据抽屉'} onClick={event=>event.stopPropagation()}><button className="drawer-close" aria-label="关闭抽屉" onClick={()=>setDrawer(undefined)}>关闭</button>{drawer==='threads'?threadsPanel:evidencePanel}</div></div>}</div>
}

export function Root(){const[token,setToken]=useState<string>();return token?<App token={token} logout={()=>setToken(undefined)}/>:<Login onAuthenticated={setToken}/>}
const rootElement=document.getElementById('root');if(rootElement)createRoot(rootElement).render(<StrictMode><Root/></StrictMode>)
